window.APPS = [
  {
    "slug": "framekit",
    "name": "Framekit",
    "job": "Put a pretty frame around a screenshot.",
    "kicker": "Frame a shot",
    "pages": "https://asherweisberger.github.io/framekit/",
    "repo": "https://github.com/AsherWeisberger/framekit",
    "originalPaid": "Xnapper",
    "shipped": "2026-08-13",
    "desktop": "./shots/framekit/desktop.png",
    "phone": "./shots/framekit/phone.png",
    "desktopAlt": "Framekit on desktop: paste or drop a screenshot, pick a background, set padding, then download.",
    "phoneAlt": "Framekit on a phone: paste a screenshot, pick a background, set padding, download.",
    "packAlign": "right"
  },
  {
    "slug": "stackpdf",
    "name": "StackPDF",
    "job": "Stick PDFs together. Or pull pages out.",
    "kicker": "Stack PDFs",
    "pages": "https://asherweisberger.github.io/stackpdf/",
    "repo": "https://github.com/AsherWeisberger/stackpdf",
    "originalPaid": "Smallpdf",
    "shipped": "2026-08-14",
    "desktop": "./shots/stackpdf/desktop.png",
    "phone": "./shots/stackpdf/phone.png",
    "desktopAlt": "StackPDF on desktop: a stack of PDFs, page picks, merge and extract in one tab.",
    "phoneAlt": "StackPDF on a phone: three files in a stack, pages selected, merge and extract in the dock."
  },
  {
    "slug": "bestcut",
    "name": "BestCut",
    "job": "Cut a video on your phone.",
    "kicker": "Cut a video",
    "pages": "https://asherweisberger.github.io/bestcut/",
    "repo": "https://github.com/AsherWeisberger/bestcut",
    "originalPaid": "CapCut",
    "shipped": "2026-08-14",
    "desktop": "./shots/bestcut/desktop.png",
    "phone": "./shots/bestcut/phone.png",
    "desktopAlt": "BestCut on desktop: media bin, 9:16 preview, inspector, four-track timeline, and dock.",
    "phoneAlt": "BestCut on a phone: 9:16 preview, four-track timeline, and the edit dock."
  },
  {
    "slug": "mattekit",
    "name": "Mattekit",
    "job": "Cut a person out of a photo.",
    "kicker": "Cut a photo",
    "pages": "https://asherweisberger.github.io/mattekit/",
    "repo": "https://github.com/AsherWeisberger/mattekit",
    "originalPaid": "Photoroom",
    "shipped": "2026-08-14",
    "desktop": "./shots/mattekit/desktop.png",
    "phone": "./shots/mattekit/phone.png",
    "desktopAlt": "Mattekit on desktop: a before/after cutout, backdrop swatches, feather and threshold, PNG export.",
    "phoneAlt": "Mattekit on a phone: before/after, backdrop swatches, matte sliders, and PNG in the dock."
  },
  {
    "slug": "cinekit",
    "name": "Cinekit",
    "job": "Record your screen. Get a movie of it.",
    "kicker": "Record a screen",
    "pages": "https://asherweisberger.github.io/cinekit/",
    "repo": "https://github.com/AsherWeisberger/cinekit",
    "originalPaid": "Screen Studio",
    "shipped": "2026-08-15",
    "desktop": "./shots/cinekit/desktop.png",
    "phone": "./shots/cinekit/phone.png",
    "desktopAlt": "Cinekit on desktop: a padded studio preview, grade rail, zoom marks on the timeline, and Record.",
    "phoneAlt": "Cinekit on a phone: the studio booth, a trim strip, and Record in the dock."
  },
  {
    "slug": "speakkit",
    "name": "Speakkit",
    "job": "Talk. The page writes it down.",
    "kicker": "Talk to type",
    "pages": "https://asherweisberger.github.io/speakkit/",
    "repo": "https://github.com/AsherWeisberger/speakkit",
    "originalPaid": "Wispr Flow",
    "shipped": "2026-08-16",
    "desktop": "./shots/speakkit/desktop.png",
    "phone": "./shots/speakkit/phone.png",
    "desktopAlt": "Speakkit on desktop: a cream speaking page, hold pad, punctuation chips, and a rail of takes.",
    "phoneAlt": "Speakkit on a phone: the page, punctuation chips, and a giant hold-to-talk dock."
  },
  {
    "slug": "swatchkit",
    "name": "Swatchkit",
    "job": "Make a color palette. Copy the codes.",
    "kicker": "Pick colors",
    "pages": "https://asherweisberger.github.io/swatchkit/",
    "repo": "https://github.com/AsherWeisberger/swatchkit",
    "originalPaid": "Coolors Pro",
    "shipped": "2026-08-17",
    "desktop": "./shots/swatchkit/desktop.png",
    "phone": "./shots/swatchkit/phone.png",
    "desktopAlt": "Swatchkit on desktop: a fan of paint chips on a dark table, OKLCH sliders, contrast, Shuffle.",
    "phoneAlt": "Swatchkit on a phone: one chip fills the sheet, hex on a cream label, Shuffle in the dock."
  },
  {
    "slug": "gleamkit",
    "name": "Gleamkit",
    "job": "Paste code. Get a picture or video of it.",
    "kicker": "Picture of code",
    "pages": "https://asherweisberger.github.io/gleamkit/",
    "repo": "https://github.com/AsherWeisberger/gleamkit",
    "originalPaid": "Snappify",
    "shipped": "2026-08-18",
    "desktop": "./shots/gleamkit/desktop.png",
    "phone": "./shots/gleamkit/phone.png",
    "desktopAlt": "Gleamkit on desktop: a Mac-chrome TypeScript shot on a sand wash, line focus, steps along the bottom.",
    "phoneAlt": "Gleamkit on a phone: the code shot fills the sheet, Play in the dock."
  },
  {
    "slug": "crushkit",
    "name": "Crushkit",
    "job": "Drop a photo. Get a smaller file.",
    "kicker": "Shrink a photo",
    "pages": "https://asherweisberger.github.io/crushkit/",
    "repo": "https://github.com/AsherWeisberger/crushkit",
    "originalPaid": "TinyPNG",
    "shipped": "2026-08-19",
    "desktop": "./shots/crushkit/desktop.png",
    "phone": "./shots/crushkit/phone.png",
    "desktopAlt": "Crushkit on desktop: a before/after photo, 1.8 MB to 297 KB, Crush and Download.",
    "phoneAlt": "Crushkit on a phone: the crushed photo fills the sheet, 1.8 MB to 297 KB, Crush in the dock."
  },
  {
    "slug": "signkit",
    "name": "Signkit",
    "job": "Open a PDF. Sign it. Download it.",
    "kicker": "Sign a PDF",
    "pages": "https://asherweisberger.github.io/signkit/",
    "repo": "https://github.com/AsherWeisberger/signkit",
    "originalPaid": "DocuSign",
    "shipped": "2026-08-20",
    "desktop": "./shots/signkit/desktop.png",
    "phone": "./shots/signkit/phone.png",
    "desktopAlt": "Signkit on desktop: a letter of agreement, a drawn signature, sand italic name, Download.",
    "phoneAlt": "Signkit on a phone: the signed page fills the sheet, Sign Type Date Save in the dock.",
    "packAlign": "center"
  },
  {
    "slug": "wavekit",
    "name": "Wavekit",
    "job": "Drop a sound. Get a waveform video.",
    "kicker": "Make a waveform",
    "pages": "https://asherweisberger.github.io/wavekit/",
    "repo": "https://github.com/AsherWeisberger/wavekit",
    "originalPaid": "Headliner",
    "shipped": "2026-08-21",
    "desktop": "./shots/wavekit/desktop.png",
    "phone": "./shots/wavekit/phone.png",
    "desktopAlt": "Wavekit on desktop: a square mirrored waveform, Friday night, Export.",
    "phoneAlt": "Wavekit on a phone: the waveform fills the sheet, Open Record Export in the dock.",
    "packAlign": "center"
  },
  {
    "slug": "fitkit",
    "name": "Fitkit",
    "job": "Drop a photo. Crop it for X, Instagram, or TikTok.",
    "kicker": "Crop a photo",
    "pages": "https://asherweisberger.github.io/fitkit/",
    "repo": "https://github.com/AsherWeisberger/fitkit",
    "originalPaid": "Canva",
    "shipped": "2026-08-22",
    "desktop": "./shots/fitkit/desktop.png",
    "phone": "./shots/fitkit/phone.png",
    "desktopAlt": "Fitkit on desktop: a crop gate on a cream table, X post 1600×900, pan and Export.",
    "phoneAlt": "Fitkit on a phone: the crop fills the sheet, Open and Export in the dock.",
    "packAlign": "center"
  },
  {
    "slug": "markkit",
    "name": "Markkit",
    "job": "Drop a screenshot. Arrow it. Blur the secrets.",
    "kicker": "Mark a screenshot",
    "pages": "https://asherweisberger.github.io/markkit/",
    "repo": "https://github.com/AsherWeisberger/markkit",
    "originalPaid": "CleanShot X",
    "shipped": "2026-08-23",
    "desktop": "./shots/markkit/desktop.png",
    "phone": "./shots/markkit/phone.png",
    "desktopAlt": "Markkit on desktop: a screenshot on a night desk, an arrow, numbered steps, blur and pixel, Export.",
    "phoneAlt": "Markkit on a phone: the marked shot fills the sheet, Open and Export in the dock.",
    "packAlign": "center"
  },
  {
    "slug": "gifkit",
    "name": "Gifkit",
    "job": "Drop a video. Get a GIF.",
    "kicker": "Make a GIF",
    "pages": "https://asherweisberger.github.io/gifkit/",
    "repo": "https://github.com/AsherWeisberger/gifkit",
    "originalPaid": "Kapwing",
    "shipped": "2026-08-24",
    "desktop": "./shots/gifkit/desktop.png",
    "phone": "./shots/gifkit/phone.png",
    "desktopAlt": "Gifkit on desktop: a film gate looping a clip, in and out on the strip, width fps speed, Make GIF.",
    "phoneAlt": "Gifkit on a phone: the loop fills the gate, the filmstrip, Open and Make GIF in the dock.",
    "packAlign": "center"
  },
  {
    "slug": "qrkit",
    "name": "Qrkit",
    "job": "Drop a link. Get a branded QR you can actually print.",
    "kicker": "Make a QR",
    "pages": "https://asherweisberger.github.io/qrkit/",
    "repo": "https://github.com/AsherWeisberger/qrkit",
    "originalPaid": "QR Code Generator PRO",
    "shipped": "2026-08-25",
    "desktop": "./shots/qrkit/desktop.png",
    "phone": "./shots/qrkit/phone.png",
    "desktopAlt": "Qrkit on desktop: a print plate with a framed SCAN ME code, type chips, ink and paper, PNG SVG PDF.",
    "phoneAlt": "Qrkit on a phone: the framed code fills the sheet, Look Save Read PNG in the dock.",
    "packAlign": "center"
  }
];
